version: '3'

services:
  app:
    build: .
    image: content-audit-tool
    command: rails server -b 0.0.0.0
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://content_audit_tool@db/content_audit_tool_production
      TEST_DATABASE_URL: postgres://content_audit_tool@db/content_audit_tool_test
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: content_audit_tool
    volumes:
      - ${DATABASE_BACKUP}:/docker-entrypoint-initdb.d/content_audit_tool_production.sql.gz
