default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: content_audit_tool_development
  url: <%= ENV['DEVELOPMENT_DATABASE_URL'] || ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: content_audit_tool_test
  url: <%= ENV['TEST_DATABASE_URL'] || ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: content_audit_tool_production
  username: content_audit_tool
  password: <%= ENV['CONTENT-AUDIT-TOOL_DATABASE_PASSWORD'] %>
